# Generated by Django 5.1.7 on 2025-03-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0002_crearpull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padelapp.match'),
        ),
    ]
