# Generated by Django 5.1.7 on 2025-03-13 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0003_alter_pull_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='pull_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padelapp.crearpull'),
        ),
    ]
