# Generated by Django 5.1.7 on 2025-03-14 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0004_pull_pull_asociada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=10)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_sueltos', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(blank=True, related_name='partidos_jugados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
