# Generated by Django 5.1.7 on 2025-03-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0005_singlematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
