# Generated by Django 5.1.7 on 2025-03-28 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0007_rename_ubicacion_match_lugar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pull', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alineacion', to='padelapp.crearpull')),
                ('suplentes', models.ManyToManyField(blank=True, related_name='suplente_en_alineaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_j1', to=settings.AUTH_USER_MODEL)),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_j2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParejaEnPista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pista', models.PositiveSmallIntegerField()),
                ('alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padelapp.alineacion')),
                ('pareja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padelapp.pareja')),
            ],
            options={
                'ordering': ['pista'],
                'unique_together': {('alineacion', 'pareja')},
            },
        ),
        migrations.AddField(
            model_name='alineacion',
            name='parejas',
            field=models.ManyToManyField(through='padelapp.ParejaEnPista', to='padelapp.pareja'),
        ),
    ]
