# Generated by Django 5.1.7 on 2025-03-31 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0008_alineacion_pareja_parejaenpista_alineacion_parejas'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tipo',
            field=models.CharField(choices=[('LAPA 3', 'LAPA 3'), ('LAPA 4', 'LAPA 4'), ('SNP 500', 'SNP 500'), ('SNP 1000', 'SNP 1000')], default='LAPA3', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='padelapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocatoriaPareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoria_pareja_j1', to=settings.AUTH_USER_MODEL)),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoria_pareja_j2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConvocatoriaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, choices=[('Titular', 'Titular'), ('Reserva', 'Reserva'), ('NoAsiste', 'No puedo asistir')], max_length=10, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_convocados', to='padelapp.convocatoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('convocatoria', 'jugador')},
            },
        ),
        migrations.CreateModel(
            name='ParejaEnPistaConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pista', models.PositiveSmallIntegerField()),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='padelapp.convocatoria')),
                ('pareja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padelapp.convocatoriapareja')),
            ],
            options={
                'ordering': ['pista'],
                'unique_together': {('convocatoria', 'pareja')},
            },
        ),
    ]
