# Generated by Django 5.1.7 on 2025-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0009_team_tipo_convocatoria_convocatoriapareja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoriajugador',
            name='respuesta',
            field=models.CharField(blank=True, choices=[('PUEDO', 'PUEDO'), ('NO PUEDO', 'NO PUEDO')], max_length=10, null=True),
        ),
    ]
