# Generated by Django 5.1.7 on 2025-03-31 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padelapp', '0010_alter_convocatoriajugador_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlineacionConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alineacion', to='padelapp.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='ParejaConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pista', models.IntegerField()),
                ('alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parejas', to='padelapp.alineacionconvocatoria')),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_conv_j1', to=settings.AUTH_USER_MODEL)),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_conv_j2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuplenteConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplentes', to='padelapp.alineacionconvocatoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
